// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import java.util.ArrayList;
import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JoinObjectsInList extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private final IMendixObject Object1;
	private final IMendixObject Object2;
	private final java.lang.String Entity;

	public JoinObjectsInList(
		IContext context,
		IMendixObject _object1,
		IMendixObject _object2,
		java.lang.String _entity
	)
	{
		super(context);
		this.Object1 = _object1;
		this.Object2 = _object2;
		this.Entity = _entity;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE

		List<IMendixObject> resultList = new ArrayList<IMendixObject>();
		resultList.add(Object1);
		resultList.add(Object2);
		return resultList;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JoinObjectsInList";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
