// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import java.util.Random;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class PickRandomPersonFromList extends CustomJavaAction<IMendixObject>
{
	/** @deprecated use com.mendix.utils.ListUtils.map(PersonList, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __PersonList;
	private final java.util.List<myfirstmodule.proxies.Person> PersonList;
	private final java.lang.String Entity;

	public PickRandomPersonFromList(
		IContext context,
		java.util.List<IMendixObject> _personList,
		java.lang.String _entity
	)
	{
		super(context);
		this.__PersonList = _personList;
		this.PersonList = java.util.Optional.ofNullable(_personList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(personListElement -> myfirstmodule.proxies.Person.initialize(getContext(), personListElement))
			.collect(java.util.stream.Collectors.toList());
		this.Entity = _entity;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		/* 		
		for (int i = 0; i < PersonList.size(); i++) {
			//System.out.println(countries.get(i));

			// Log from JavaAction to console
			ILogNode logger2 = Core.getLogger("PickRandomPersonFromList");
			logger2.info(PersonList.get(i));		
		}
		ILogNode logger1 = Core.getLogger("PickRandomPersonFromList");
		logger1.info(PersonList.get(1).getMendixObject());		
		*/

		Random rand = new Random();
		int n = rand.nextInt(PersonList.size());

		return PersonList.get(n).getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PickRandomPersonFromList";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
