// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class CoffeeBreak implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject coffeeBreakMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.CoffeeBreak";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CoffeeBreakID("CoffeeBreakID");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CoffeeBreak(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CoffeeBreak(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject coffeeBreakMendixObject)
	{
		if (coffeeBreakMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, coffeeBreakMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.coffeeBreakMendixObject = coffeeBreakMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.CoffeeBreak initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.CoffeeBreak(context, mendixObject);
	}

	public static myfirstmodule.proxies.CoffeeBreak load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.CoffeeBreak.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.CoffeeBreak> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.CoffeeBreak.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of CoffeeBreakID
	 */
	public final java.lang.Long getCoffeeBreakID()
	{
		return getCoffeeBreakID(getContext());
	}

	/**
	 * @param context
	 * @return value of CoffeeBreakID
	 */
	public final java.lang.Long getCoffeeBreakID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.CoffeeBreakID.toString());
	}

	/**
	 * Set value of CoffeeBreakID
	 * @param coffeebreakid
	 */
	public final void setCoffeeBreakID(java.lang.Long coffeebreakid)
	{
		setCoffeeBreakID(getContext(), coffeebreakid);
	}

	/**
	 * Set value of CoffeeBreakID
	 * @param context
	 * @param coffeebreakid
	 */
	public final void setCoffeeBreakID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long coffeebreakid)
	{
		getMendixObject().setValue(context, MemberNames.CoffeeBreakID.toString(), coffeebreakid);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return coffeeBreakMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.CoffeeBreak that = (myfirstmodule.proxies.CoffeeBreak) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
