// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder addPersonBuilder(
		myfirstmodule.proxies.CoffeeBreak _coffeeBreak
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.AddPerson");
		builder = builder.withParam("CoffeeBreak", _coffeeBreak);
		return builder;
	}

	public static void addPerson(
		IContext context,
		myfirstmodule.proxies.CoffeeBreak _coffeeBreak
	)
	{
		addPersonBuilder(
				_coffeeBreak
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder createCoffeeBreakBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.CreateCoffeeBreak");
		return builder;
	}

	public static void createCoffeeBreak(IContext context)
	{
		createCoffeeBreakBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder createProductBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.CreateProduct");
		return builder;
	}

	public static void createProduct(IContext context)
	{
		createProductBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder getProductBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.GetProduct");
		return builder;
	}

	public static void getProduct(IContext context)
	{
		getProductBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder getProduct_2Builder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.GetProduct_2");
		return builder;
	}

	public static void getProduct_2(IContext context)
	{
		getProduct_2Builder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder pickPersonBuilder(
		myfirstmodule.proxies.CoffeeBreak _coffeeBreak
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.PickPerson");
		builder = builder.withParam("CoffeeBreak", _coffeeBreak);
		return builder;
	}

	public static void pickPerson(
		IContext context,
		myfirstmodule.proxies.CoffeeBreak _coffeeBreak
	)
	{
		pickPersonBuilder(
				_coffeeBreak
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder product_Get_AllBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.Product_Get_All");
		return builder;
	}

	public static java.util.List<myfirstmodule.proxies.Product> product_Get_All(IContext context)
	{
		Object result = product_Get_AllBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> myfirstmodule.proxies.Product.initialize(context, obj));
	}
}
